language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test &&
  travis-cargo --only nightly bench &&
  travis-cargo --only stable doc
after_success:
- travis-cargo --only stable doc-upload
- travis-cargo coveralls --no-sudo
env:
  global:
  - matrix:
    - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
  - secure: On2QkVjG28RaQ1hcWMwUCVfTd2H7V8X+61E8h/wYXmpD9JAwGsS4SHbYC3SZMi7B5+yBXENtiXsWXRVfCP4fjTf0j/fMJIjtU4yE1WE+XRR7t3qBatD5KVZ5bR6g6RFsDJhsQOxRTQD31OCK0lGPbBA4uESaWx+9VtyVSH64jP0KCyycTSIM032cTUMqs7gSuMvhoHgNxSFjz5h9EkrxmiwBM0xb07sWskLp5v0+9LWaP8cgOWXMm67KnI8PQVajRi/8HXXm8vZrkTFx68CDm1YbLQQY0RDWyz79JW6rvV/GPpn6pJhhMLOZN9dj+UeFVY92ayDeHeFVY5ttnblinz3VBQLvBwoTj5DMvdwPyKRiOgEGkL6PTn6KzXUcHgOjrxsF5+jK2L+G3HajQ/8fZpCU+ujFxm/Wr6UgFeBV+bFIlPnDPtF7drhj89g/EfxN8PhOyPVoua1kgE2Tqq4YP5/txNkTeutVKqk5L31jozEhnCmDuuiHOKYVL0FW8RItuIXk9qOPuYLKvTTRmOn3IZg6+QhA4WAeIF0JPvjCVuWtXWiZWH6RE9z3NWB+tqXn/HnNluFaajw6i2NfepssaoySNefCQruyMH76sr5jnI/jg6sN+ftewOxfhgz583mrwIHPznMN4achc3owcfxctGiQmj7p1B977+8Mi8tjqGs=
